# -Refs
#   - github actionsの基礎
#     - https://blog1.mammb.com/entry/2021/12/11/090000
#   - 変数関連
#     - https://dev.classmethod.jp/articles/replace-deprecated-method-on-actions/
#   - 実行ユーザ関連
#     - https://qiita.com/thaim/items/3d1a4d09ec4a7d8844ce
#     - https://zenn.dev/tatsuo48/articles/72c8939bbc6329
#     - https://rcmdnk.com/blog/2022/09/29/computer-github/
#   - 新しいブランチを切ってプルリクする関連
#     - https://www.ritolab.com/posts/206
#     - https://www.memory-lovers.blog/entry/2022/11/18/083000
#     - https://michaelcurrin.github.io/code-cookbook/recipes/ci-cd/github-actions/workflows/create-pull-request.html
#   - プルリクマージ関連
#     - https://zenn.dev/tatsurom/articles/actions-auto-merge
#   - ファイル作成～プルリクまで
#     - https://dev.classmethod.jp/articles/creating-a-file-branch-pull-request-from-github-actions-by-issue-event/


name: download_zenn_posts
on:
  # mainブランチへのプルリクマージをトリガーにする
  # - Refs
  #   - https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    # https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      # environment:
      #   description: 'Environment to run tests against'
      #   type: environment
      #   required: true
jobs:
  download_zenn_posts:
    if:
      # https://docs.github.com/ja/actions/learn-github-actions/expressions
      (github.event_name == 'workflow_dispatch') ||
      ((github.event_name == 'workflow_dispatch') && (github.event.pull_request.merged == true))
    runs-on: ubuntu-latest
    env:
      # 一定の記事数を超えると全件取得できなくなってくるかも．count/pageといったパラメータを意識する必要が出てくる．
      API_ZENN_ARTICLES: https://zenn.dev/api/articles?username=hellodeafworld
      API_ZENN_BOOKS: https://zenn.dev/api/books?username=hellodeafworld
      API_ZENN_SCRAPS: https://zenn.dev/api/scraps?username=hellodeafworld
    steps:
      - name: checkout main-github_actions
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v3
        with:
          ref: main-github_actions
      # - name: create new branch
      #   env:
      #     TZ: 'Asia/Tokyo'
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   run: |
      #     job_time=$(date '+%Y%m%d%H%M')
      #     branch_name=github_actions/zenn_articles-${job_time}
      #     echo "BRANCH_NAME=${branch_name}" >> $GITHUB_ENV
      #     # 前のstepで新しいブランチの作成元にcheckoutしてある前提
      #     git checkout -b ${branch_name}
      - name: download and output zenn articles into a json
        run: |
          # pwd
          # echo ${GITHUB_WORKSPACE}
          # ls -la
          curl ${API_ZENN_ARTICLES} > ${GITHUB_WORKSPACE}/github_actions/zenn_articles/download.json
          ls -la .
          cat ${GITHUB_WORKSPACE}/github_actions/zenn_articles/download.json
      # - name: create pull request
      #   # https://github.com/marketplace/actions/create-pull-request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     title: Merge new zenn articles json
      #     commit-message: Merge new zenn articles json
      #     branch: $branch_name ???
      #     base: main-github_actions
